default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  pool: 5

development:
  <<: *default
  database: tweetland_development

test:
  <<: *default
  database: tweetland_test
